### PR TITLE
chore: add licence to package.json

### PR DESCRIPTION
**Pull request by smellyshovel**
Fix licence for the npm site.

### CODE REVIEW

**Review by wipfli — APPROVED** [review]

**Comment by wipfli** [comment]
I added you as an admin of this repo. Did you get an invite?

**Comment by smellyshovel** [comment]
@wipfli sure, I've approved a couple of your PRs already :) Just didn't merge them.

**Comment by smellyshovel** [comment]
@wipfli I'll anyway stick to the PR->approve->merge workflow, even despite that I'm granted with admin perms.

**Comment by wipfli** [comment]
That is good. I think it is always possible to approve a pull request, even if you don't have any access rights on a repo. In your case, you approved my pull requests before but then your vote did not count so the merge button was still red and said that I had to use my admin privileges to merge (which I did use...).

**Pull request merged**
