### PR TITLE
Preserve the "hover" state for waypoints after their creation and movement

### LINKED ISSUE #232: Does not register mouse is hovering
When moving a waypoint, you cannot move it again without first moving the cursor outside and then back inside (usually).

https://github.com/user-attachments/assets/26737977-8467-493a-809e-edf9104d84e8

### PR DESCRIPTION
**Pull request by smellyshovel**
Closes #232.

### CODE REVIEW

**Comment by joleeee** [comment]
Hi, are there install instructions? `.nvmrc` says 16, but when i try to install with node 16 i get that a bunch of things require >=18.

**Comment by smellyshovel** [comment]
> Hi, are there install instructions? `.nvmrc` says 16, but when i try to install with node 16 i get that a bunch of things require >=18.

Everything's documented in the CONTRIBUTING.md.
Regarding the Node version - it easily may be so. The deps were updated a lot of times, but I haven't touched the .nvmrc, so it's probably outdated. Feel free to fix it.

**Review by Miguel-Sanches — APPROVED** [review]

**Comment by joleeee** [comment]
Definitely still some funky stuff going on

https://github.com/user-attachments/assets/d26c6737-e26d-47a2-adab-ca3fe9623fb8

**Comment by smellyshovel** [comment]
> Definitely still some funky stuff going on (rev [84d6622](https://github.com/maplibre/maplibre-gl-directions/commit/84d66228df8884184e2136eaa7b95f63df030cbd))
> 
>  rec.mp4

Got it. Haven't tested with delayed responses. So, the 2 tickets you've created must be related somehow.
Apparently, the interactivity gets disabled while there's an ongoing request, and this fix contradicts that.
So, this will require a further look.

Closing this PR for now.

**Pull request closed without merging**
