### PR TITLE
Re-enable plugin's disabled interactivity even if a routing-request fails. Equalize routing and other errors.

### LINKED ISSUE #25: Handle routing errors?
At the time being it's assumed that the user takes care of the failing routing-requests themselves. E.g. by wrapping the `.addWaypoint` inside the `try-catch` block.

Maybe it's worth of providing some default error-handling so that the whole thing doesn't fail in case it's not wrapper in `try-catch`?

### PR DESCRIPTION
**Pull request by smellyshovel**
**Branched out of #75**.

Routing errors (server responses with status status code 4xx e.g.) where `response.code !== "Ok"` are treated the same way as general errors (like a lost network connection). These errors are not indeed handled somehow. I decided to simply throw exceptions instead to let the user decide what to do with them. The only place where it's decided by me is when dragging a waypoint. In such case if an error occurs, the waypoint's initial position is restored back and that's it.

Closes #25, but it a slightly different manner. Instead of manually handling all the possible errors the errors are thrown as they are, but the disabled plugin's interactivity is re-enabled even if there was an error.

### CODE REVIEW

**Comment by wipfli** [comment]
@smellyshovel with follow up pull requests, what is the best workflow for me when I review them? I am surprised that there are conflicts. Can GitHub not resolve these and just show me a minimal diff?

**Comment by smellyshovel** [comment]
@wipfli not sure. I'm trying to divide PRs into minimal independent changes, but one change relies on another feature (that is another PR that has to be merged first). I'll merge main into respective branches where necessary manually.

**Comment by smellyshovel** [comment]
@wipfli I think the best workflow would be to after merging some PR merge the updated main brain into the branch that is dedicated for the follow-up-PR. I think my fork's branches are opened for you to contribute. I can also do that myself (and I did for that very PR just yet), but then we need to synchronize our time to be available for each other for some time straight without.

I don't like the way it's now either, but that's how I work. Implement one feature, branch out of there, implement another one that depends on the prev. one and so on. Maybe there's a better approach but I'm not aware of it.

**Comment by smellyshovel** [comment]
Strange thing is that I don't see a conflict in the other software I use...

**Comment by wipfli** [comment]
Yeah it is so strange... But OK, when reviewing I can also merge main for subsequent pull requests...

**Comment by smellyshovel** [comment]
@wipfli I think I know where it came from for the PR. Most probably you merged some PR first that this one depends one.

**Comment by wipfli** [comment]
I though I only merged the code of conduct pull request.

**Comment by wipfli** [comment]
Just to double-check, we do have auto-formatting and linting turned on in CI for this repo, no? The conflicts look like white-space related...

**Comment by wipfli** [comment]
Ah no, we don't have linting in CI. Can you add something like this: https://github.com/maplibre/maplibre-gl-js/blob/main/.github/workflows/lint.yml ?

**Comment by smellyshovel** [comment]
@wipfli we do have linting in CI. It's a part of the main workflow. Though it doesn't automatically commit the changes. But that's another story for another PR.

The conflicts don't seem white-space-related to me. It's of some another sort. Probably that if no. 76 is branched out from no.75 then it should first be merged into no. 76 and only then into main. Not sure.
Screenshot_20220514_195151

**Comment by wipfli** [comment]
Ah nice that linting is there. Sorry if I mixed up the order of the pull requests.

**Comment by smellyshovel** [comment]
@wipfli no, you probably did not. I don't know the root of the issue. I'll try to resolve everything by maximum and will ping you when it's all ready to merge.

**Comment by wipfli** [comment]
That's great, thanks!

**Comment by smellyshovel** [comment]
@wipfli I'll now close that one and will open another one. Hopefully there'll be no conflicts.

**Pull request closed without merging**
