### PR TITLE
Use higher-perms token when checking the repo out to grant pushing perms

### PR DESCRIPTION
**Pull request by smellyshovel**
I've added another secret to the repo with higher permissions to allow to bypass branch-protection rules.

### CODE REVIEW

**Comment by smellyshovel** [comment]
Just tried it out with the same branch protection rules on my fork (and with the same secret key) - works.
I'll remove the release now and un-draft the PR.

Screenshot_20220419_210425

**Comment by smellyshovel** [comment]
@wipfli Done. I think this one could be safely merged. Feel free to reconsider the token's scopes (if you think some perms are excessive).

**Comment by wipfli** [comment]
Ah interesting, is `GH_TOKEN` a PAT or something? https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by smellyshovel** [comment]
@wipfli exactly

**Comment by smellyshovel** [comment]
@wipfli we can create an organization-wise one. If it's possible. Or you can use your own. Or we can leave mine. Doesn't matter to me.

**Review by wipfli — APPROVED** [review]
OK then let's try this. Please document this in a readme somewhere...

**Comment by smellyshovel** [comment]
@wipfli I think we can call this a victory :)

I'll update the README a bit later. Or maybe I should rather include that in CONTRUBUTING.md?

**Comment by wipfli** [comment]
Contributing seems the right place to me.

**Pull request merged**
