### PR TITLE
Reconsider MapLibre dependencies' versions and other small dev-updates

### LINKED ISSUE #4: nvm
For new contributors, it is nice to tell them which node / npm version is necessary. In GL JS, we have some documentation about using `nvm use` together with a `.nvmrc` file which we set to 16 I think. @smellyshovel can you add something like this here as well?

### PR DESCRIPTION
**Pull request by smellyshovel**
- chore: update maplibre and set proper deps versions
- chore: reconsider types after maplibre update
- chore: reconsider the contributing guide
- close #4

### CODE REVIEW

**Comment by wipfli** [comment]
Can you comment on the maplibre version?

**Comment by smellyshovel** [comment]
@wipfli the plugin should not be used with maplibre-gl under 2.1.0 (didn't test with earlier versions, it may work fine with 2.0.x, I don't know). But for the dev-environment it must not be less than 2.1.8, because 2.1.8 includes some necessary TS-fixes.

**Comment by smellyshovel** [comment]
The plugin might even work with well with maplibre 1.x.x, didn't test as well. I can test it later.

**Comment by smellyshovel** [comment]
@wipfli ready to merge. One more is on its way and is gonna be created as soon as this one's merged (to reduce the confusion).

**Review by wipfli — APPROVED** [review]

**Pull request merged**
